# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure FMD Server paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ findmydeviceserver_uid }}"
    group: "{{ findmydeviceserver_gid }}"
  with_items:
    - "{{ findmydeviceserver_base_path }}"

- name: Ensure FMD Server support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ findmydeviceserver_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ findmydeviceserver_uid }}"
    group: "{{ findmydeviceserver_gid }}"
  with_items:
    - config.yml
    - env
    - labels

- name: Ensure FMD Server container image is pulled
  community.docker.docker_image:
    name: "{{ findmydeviceserver_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ findmydeviceserver_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else findmydeviceserver_container_image_force_pull }}"

- name: Ensure FMD Server container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ findmydeviceserver_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure FMD Server systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/findmydeviceserver.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ findmydeviceserver_identifier }}.service"
    mode: "0644"
